USE mysql;

DROP FUNCTION IF EXISTS lib_mysqludf_xql_info;
DROP FUNCTION IF EXISTS xql_textdecl;
DROP FUNCTION IF EXISTS xql_pi;
DROP FUNCTION IF EXISTS xql_dtd;
DROP FUNCTION IF EXISTS xql_element;
DROP FUNCTION IF EXISTS xql_forest;
DROP FUNCTION IF EXISTS xql_concat;
DROP FUNCTION IF EXISTS xql_agg;
DROP FUNCTION IF EXISTS xql_comment;
DROP FUNCTION IF EXISTS xql_cdata;
DROP FUNCTION IF EXISTS xql_encode;
